# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-07-09 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_order_placed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_placed',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
